services:
  mysql:
    image: mysql:latest
    container_name: telegram_weather_bot_mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Subscriptions
      MYSQL_USER: user                   
      MYSQL_PASSWORD: password           
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql        

volumes:
  mysql_data:
